# Generated by Django 3.0.6 on 2020-06-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=20, null=True)),
                ('visit_date', models.DateField(blank=True, verbose_name='Conversation Date')),
                ('visit_time', models.TimeField(blank=True, verbose_name='Conversation Time')),
            ],
        ),
        migrations.CreateModel(
            name='FundsActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=20, null=True)),
                ('visit_date', models.DateField(blank=True, verbose_name='Conversation Date')),
                ('visit_time', models.TimeField(blank=True, verbose_name='Conversation Time')),
            ],
        ),
        migrations.CreateModel(
            name='LandingPageVisitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(blank=True, verbose_name='Conversation Date')),
                ('visit_time', models.TimeField(blank=True, verbose_name='Conversation Time')),
            ],
        ),
        migrations.CreateModel(
            name='LoanActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=20, null=True)),
                ('visit_date', models.DateField(blank=True, verbose_name='Conversation Date')),
                ('visit_time', models.TimeField(blank=True, verbose_name='Conversation Time')),
            ],
        ),
        migrations.CreateModel(
            name='TableDummy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_dummy', models.CharField(max_length=20)),
            ],
        ),
    ]
