# Generated by Django 3.0.6 on 2020-06-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0002_loginactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=20, null=True)),
                ('visit_date', models.DateField(blank=True, verbose_name='Conversation Date')),
                ('visit_time', models.TimeField(blank=True, verbose_name='Conversation Time')),
            ],
        ),
        migrations.DeleteModel(
            name='TableDummy',
        ),
    ]
