# Generated by Django 3.0.6 on 2020-06-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0003_auto_20200601_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionMange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
